# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

Sim, pode. Uma matriz pode receber vetores, pois ela é formada por várias linhas (ou colunas), e cada uma delas pode ser um vetor.

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [3]:
lista_HDACS = ["HDAC1", "HDAC2", "HDAC3", "HDAC4", "HDAC5"]
lista_HDACS

['HDAC1', 'HDAC2', 'HDAC3', 'HDAC4', 'HDAC5']

In [4]:
lista_HDAC1 = [
    len(lista_HDACS[0]), 
    lista_HDACS [0] [:2], 
    lista_HDACS [0].count ("A"), 
    "hu" in lista_HDACS [0]
]
print (lista_HDAC1)

[5, 'HD', 1, False]

In [5]:
lista_HDAC2 = [
    len(lista_HDACS[1]), 
    lista_HDACS [1] [:2], 
    lista_HDACS [1].count ("A"), 
    "hu" in lista_HDACS [1]
]
print (lista_HDAC2)

[5, 'HD', 1, False]

In [6]:
lista_HDAC3 = [
    len(lista_HDACS[2]), 
    lista_HDACS [2] [:2], 
    lista_HDACS [2].count ("A"), 
    "hu" in lista_HDACS [2]
]
print (lista_HDAC3)

[5, 'HD', 1, False]

In [7]:
lista_HDAC4 = [
    len(lista_HDACS[3]), 
    lista_HDACS [3] [:2], 
    lista_HDACS [3].count ("A"), 
    "hu" in lista_HDACS [3]
]
print (lista_HDAC4)

[5, 'HD', 1, False]

In [8]:
lista_HDAC5 = [
    len(lista_HDACS[4]), 
    lista_HDACS [4] [:2], 
    lista_HDACS [4].count ("A"), 
    "hu" in lista_HDACS [4]
]
print (lista_HDAC5)

[5, 'HD', 1, False]

In [10]:
matriz_HDACS = [lista_HDAC1, lista_HDAC2, lista_HDAC3, lista_HDAC4, lista_HDAC5]
matriz_HDACS

[[5, 'HD', 1, False],
 [5, 'HD', 1, False],
 [5, 'HD', 1, False],
 [5, 'HD', 1, False],
 [5, 'HD', 1, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [13]:
import numpy as np
array_HDACS = np.array(matriz_HDACS)
array_HDACS

array([['5', 'HD', '1', 'False'],
       ['5', 'HD', '1', 'False'],
       ['5', 'HD', '1', 'False'],
       ['5', 'HD', '1', 'False'],
       ['5', 'HD', '1', 'False']], dtype='<U21')

## 4 – Recupere todos os itens do terceiro gene.

In [16]:
array_HDACS[2]

array(['5', 'HD', '1', 'False'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [24]:
print (array_HDACS[: ,-1])

['False' 'False' 'False' 'False' 'False']

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [25]:
print (array_HDACS[1, 1:3])
print (array_HDACS[3, 1:3])

['HD' '1']
['HD' '1']

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [ ]:
dicionario_HDACS = {
    lista_HDACS[0]:lista_HDAC1,
    lista_HDACS[1]:lista_HDAC2,
    lista_HDACS[2]:lista_HDAC3,
    lista_HDACS[3]:lista_HDAC4,
    lista_HDACS[4]:lista_HDAC5
}
print (dicionario_HDACS)

{'HDAC1': [5, 'HD', 1, False], 'HDAC2': [5, 'HD', 1, False], 'HDAC3': [5, 'HD', 1, False], 'HDAC4': [5, 'HD', 1, False], 'HDAC5': [5, 'HD', 1, False]}

In [29]:
import pandas as pd

In [30]:
df_HDACS = pd.DataFrame(dicionario_HDACS)
df_HDACS

   HDAC1  HDAC2  HDAC3  HDAC4  HDAC5
0      5      5      5      5      5
1     HD     HD     HD     HD     HD
2      1      1      1      1      1
3  False  False  False  False  False

In [37]:
df_HDACS.index = ["Caracteres", "Inicio_nomes", "Contagem_A", "Tem_HU"]
df_HDACS

              HDAC1  HDAC2  HDAC3  HDAC4  HDAC5
Caracteres        5      5      5      5      5
Inicio_nomes     HD     HD     HD     HD     HD
Contagem_A        1      1      1      1      1
Tem_HU        False  False  False  False  False

In [72]:
df_HDACS2 = df_HDACS.T
df_HDACS2

      Caracteres Inicio_nomes Contagem_A Tem_HU
HDAC1          5           HD          1  False
HDAC2          5           HD          1  False
HDAC3          5           HD          1  False
HDAC4          5           HD          1  False
HDAC5          5           HD          1  False

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [79]:
print (df_HDACS2[['Caracteres', 'Contagem_A']])

      Caracteres Contagem_A
HDAC1          5          1
HDAC2          5          1
HDAC3          5          1
HDAC4          5          1
HDAC5          5          1

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [82]:
print (df_HDACS2.iloc[[0,2]]['Tem_HU'])

HDAC1    False
HDAC3    False
Name: Tem_HU, dtype: object

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [86]:
df_Flórida2012 = pd.read_csv('data.csv')
df_Flórida2012

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36629,404309,FL,PINELLAS COUNTY,0.0,88722.00,0.0,88722.0,88722.00,155065.65,0.0,0.0,0.0,0,28.122885,-82.770218,Residential,Wood,3
36630,465875,FL,PINELLAS COUNTY,1297057.5,1297057.50,1297057.5,1297057.5,1297057.50,1577500.79,0.0,0.0,0.0,0,28.080900,-82.758800,Residential,Masonry,1
36631,791209,FL,PINELLAS COUNTY,173286.9,173286.90,0.0,0.0,173286.90,205527.97,0.0,0.0,0.0,0,28.110550,-82.766360,Residential,Wood,4
36632,322627,FL,PINELLAS COUNTY,1499781.6,1499781.60,0.0,0.0,1499781.60,1768782.43,0.0,0.0,0.0,0,28.089415,-82.697411,Residential,Masonry,3
36633,398149,FL,PINELLAS COUNTY,373488.3,373488.30,0.0,0.0,373488.30,596003.67,0.0,0.0,0.0,0,28.064440,-82.774590,Residential,Masonry,1

In [87]:
entradas = df_Flórida2012.shape
entradas

(36634, 18)

In [110]:
classes = list(df_Flórida2012.dtypes.unique())
classes

[dtype('int64'), dtype('O'), dtype('float64')]

In [96]:
n_classes = df_Flórida2012.dtypes.value_counts()
n_classes

float64    11
object      4
int64       3
Name: count, dtype: int64

In [97]:
colunas = df_Flórida2012.iloc [: , [0, 3, 8]]
colunas

       policyID  eq_site_limit    tiv_2012
0        119736       498960.0   792148.90
1        448094      1322376.3  1438163.57
2        206893       190724.4   192476.78
3        333743            0.0    86854.48
4        172534            0.0   246144.49
...         ...            ...         ...
36629    404309            0.0   155065.65
36630    465875      1297057.5  1577500.79
36631    791209       173286.9   205527.97
36632    322627      1499781.6  1768782.43
36633    398149       373488.3   596003.67

[36634 rows x 3 columns]

In [99]:
media = colunas.mean()
media

policyID         5.486619e+05
eq_site_limit    7.314780e+05
tiv_2012         2.571004e+06
dtype: float64

In [104]:
desv_pad = colunas.std()
desv_pad

policyID         2.599129e+05
eq_site_limit    1.752300e+07
tiv_2012         2.036777e+07
dtype: float64

In [105]:
terc_quartil = colunas.quantile(0.75)
terc_quartil

policyID         7.742520e+05
eq_site_limit    0.000000e+00
tiv_2012         1.128871e+06
Name: 0.75, dtype: float64

In [111]:
dicionario_Florida2012 = {
    'N_ENTRADAS': entradas,
    'CLASSES': classes,  
    'N_CLASSES': n_classes,
    'MÉDIAS': media,
    'D_PAD': desv_pad, 
    '3Q': terc_quartil 
}
dicionario_Florida2012

{'N_ENTRADAS': (36634, 18),
 'CLASSES': [dtype('int64'), dtype('O'), dtype('float64')],
 'N_CLASSES': float64    11
 object      4
 int64       3
 Name: count, dtype: int64,
 'MÉDIAS': policyID         5.486619e+05
 eq_site_limit    7.314780e+05
 tiv_2012         2.571004e+06
 dtype: float64,
 'D_PAD': policyID         2.599129e+05
 eq_site_limit    1.752300e+07
 tiv_2012         2.036777e+07
 dtype: float64,
 '3Q': policyID         7.742520e+05
 eq_site_limit    0.000000e+00
 tiv_2012         1.128871e+06
 Name: 0.75, dtype: float64}