# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [3]:
a = 2.0 + 3.0 / 5.0
b = (a + 10.2) - 5.0 * 2.0
c = a / b + 33.8
d = a / (b + c)
e = d * 2
print(a)
print(b)
print(c)
print(d)
print(e)

2.6
2.799999999999999
34.72857142857143
0.0692805481537876
0.1385610963075752

## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [ ]:
lista_a = [2.0, 3.0, 5.0] + [10, 20, 30]
lista_b = lista_a * 2
lista_c = lista_a + lista_b
lista_d = lista_a / (lista_b * lista_c)

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
# A lista D não é possível realizar pois é uma sequencia não inteira do tipo lista., sendo assim não se pode fazer a multiplicação ou divisão entre duas listas.
print (lista_a)
print (lista_b)
print (lista_c)

[2.0, 3.0, 5.0, 10, 20, 30]
[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]
[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]

## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [65]:
valor_a = 2.6
valor_b = 2.799999999999999
valor_c = 34.72857142857143
valor_d = 0.0692805481537876
valor_e = 0.1385610963075752
lista_1 = [valor_a, valor_b, valor_c, valor_d, valor_e]
lista_2 = [x ** 0.5 for x in lista_1]
lista_3 = [lista_1 + lista_2]
lista_3

[[2.6,
  2.799999999999999,
  34.72857142857143,
  0.0692805481537876,
  0.1385610963075752,
  1.61245154965971,
  1.6733200530681507,
  5.893095233285427,
  0.263211983302029,
  0.3722379565648501]]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [66]:
import numpy as np
lista_duplicada = lista_3 * 2
array = np.array(lista_duplicada)
array

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055,  0.1385611 ,
         1.61245155,  1.67332005,  5.89309523,  0.26321198,  0.37223796],
       [ 2.6       ,  2.8       , 34.72857143,  0.06928055,  0.1385611 ,
         1.61245155,  1.67332005,  5.89309523,  0.26321198,  0.37223796]])

In [67]:
array.shape

(2, 10)

In [68]:
array_remodelado = array.reshape(5,4)
print(array_remodelado)
print(array_remodelado.shape)

[[ 2.6         2.8        34.72857143  0.06928055]
 [ 0.1385611   1.61245155  1.67332005  5.89309523]
 [ 0.26321198  0.37223796  2.6         2.8       ]
 [34.72857143  0.06928055  0.1385611   1.61245155]
 [ 1.67332005  5.89309523  0.26321198  0.37223796]]
(5, 4)

## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [69]:
lista_medias = array_remodelado.mean (axis=0).tolist()
print(lista_medias)

[7.8807329122498375, 2.1494130575327546, 7.8807329122498375, 2.149413057532755]

## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [70]:
array.shape

(2, 10)

In [71]:
array_medias = np.append(array_remodelado, [lista_medias], axis=0)
print(array_medias)
array_medias.shape

[[ 2.6         2.8        34.72857143  0.06928055]
 [ 0.1385611   1.61245155  1.67332005  5.89309523]
 [ 0.26321198  0.37223796  2.6         2.8       ]
 [34.72857143  0.06928055  0.1385611   1.61245155]
 [ 1.67332005  5.89309523  0.26321198  0.37223796]
 [ 7.88073291  2.14941306  7.88073291  2.14941306]]

(6, 4)

## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [72]:
import pandas as pd

In [90]:
#O array já possui 4 colunas
df  = pd.DataFrame(array_medias).round(3)
print(df)

        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149

## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [91]:
df_aritmetico2 = df.iloc [:]
df

        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149

In [92]:
df_aritmetico2["Media"] = df.mean(axis=1)
df_aritmetico2

        0      1       2      3     Media
0   2.600  2.800  34.729  0.069  10.04950
1   0.139  1.612   1.673  5.893   2.32925
2   0.263  0.372   2.600  2.800   1.50875
3  34.729  0.069   0.139  1.612   9.13725
4   1.673  5.893   0.263  0.372   2.05025
5   7.881  2.149   7.881  2.149   5.01500

## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [96]:
df_describe1 = df_aritmetico2.describe()
df_describe1

               0         1          2         3      Media
count   6.000000  6.000000   6.000000  6.000000   6.000000
mean    7.880833  2.149167   7.880833  2.149167   5.015000
std    13.455228  2.107787  13.455228  2.107787   3.758615
min     0.139000  0.069000   0.139000  0.069000   1.508750
25%     0.615500  0.682000   0.615500  0.682000   2.120000
50%     2.136500  1.880500   2.136500  1.880500   3.672125
75%     6.560750  2.637250   6.560750  2.637250   8.106688
max    34.729000  5.893000  34.729000  5.893000  10.049500

In [94]:
ultima_linha = df_describe1.iloc[-1]
ultima_coluna = df_describe1.iloc[:, -1]
df_transpose= df_describe1.transpose()
print(ultima_coluna)
print(ultima_linha)
print(df_transpose)

count     6.000000
mean      5.015000
std       3.758615
min       1.508750
25%       2.120000
50%       3.672125
75%       8.106688
max      10.049500
Name: Media, dtype: float64
0        34.7290
1         5.8930
2        34.7290
3         5.8930
Media    10.0495
Name: max, dtype: float64
       count      mean        std      min     25%       50%       75%  \
0        6.0  7.880833  13.455228  0.13900  0.6155  2.136500  6.560750
1        6.0  2.149167   2.107787  0.06900  0.6820  1.880500  2.637250
2        6.0  7.880833  13.455228  0.13900  0.6155  2.136500  6.560750
3        6.0  2.149167   2.107787  0.06900  0.6820  1.880500  2.637250
Media    6.0  5.015000   3.758615  1.50875  2.1200  3.672125  8.106688

           max
0      34.7290
1       5.8930
2      34.7290
3       5.8930
Media  10.0495

In [85]:
print("Última linha (max de cada coluna):")
print(ultima_linha)

print("\nÚltima coluna (estatísticas da última variável):")
print(ultima_coluna)

Última linha (max de cada coluna):
0        34.7290
1         5.8930
2        34.7290
3         5.8930
Media    10.0495
Name: max, dtype: float64

Última coluna (estatísticas da última variável):
count     6.000000
mean      5.015000
std       3.758615
min       1.508750
25%       2.120000
50%       3.672125
75%       8.106688
max      10.049500
Name: Media, dtype: float64

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [97]:
df_aritmetico2

        0      1       2      3     Media
0   2.600  2.800  34.729  0.069  10.04950
1   0.139  1.612   1.673  5.893   2.32925
2   0.263  0.372   2.600  2.800   1.50875
3  34.729  0.069   0.139  1.612   9.13725
4   1.673  5.893   0.263  0.372   2.05025
5   7.881  2.149   7.881  2.149   5.01500

In [99]:
df_aritmetico2.rename(index={df_aritmetico2.index[-1]: "Media_Colunas"}, inplace=True)
df_aritmetico2

                    0      1       2      3     Media
0               2.600  2.800  34.729  0.069  10.04950
1               0.139  1.612   1.673  5.893   2.32925
2               0.263  0.372   2.600  2.800   1.50875
3              34.729  0.069   0.139  1.612   9.13725
4               1.673  5.893   0.263  0.372   2.05025
Media_Colunas   7.881  2.149   7.881  2.149   5.01500

In [101]:
#Como no inicio eu fiz a média das colunas(exercicio 5 e 6), e depois a média das linhas (exercicio 8), assim o valor do canto inferior direito, é a média da média.
print(df_aritmetico2.iloc[-1, -1])

5.015000000000001